[8.0.1.0.0]-[product_category_workflow]
open-synergy/opnsynid-product-attribute pull request #37
Opened 2020-05-05 09:56 UTC by azmimr67

Product Category Work Flow
Plus check validasi saat restart

2020-05-10 23:02 UTC, mikevhe18 requested changes

2020-05-10 23:02 UTC, mikevhe18 commented on product_category_workflow_policy/models/product_category.py
> +
Error E302.
Sebelum class harus dibuat jarak 2 baris.

2020-05-10 23:02 UTC, mikevhe18 commented on product_category_workflow_policy/models/product_category.py
> +
Error E304.
Sehabis penulisan decorator, tidak usah dikasi baris/enter

2020-05-10 23:02 UTC, mikevhe18 commented on product_category_workflow_policy/models/product_category.py
> +        states={"draft": [("readonly", False),]},
Error E231.
Sehabis koma harus dikasih spasi 1

2020-05-10 23:02 UTC, mikevhe18 commented on product_category_workflow_policy/models/product_category.py
> +        states={"draft": [("readonly", False),]},
Error E231.
Sehabis koma harus dikasih spasi 1

2020-05-10 23:02 UTC, mikevhe18 commented on product_category_workflow_policy/models/product_category.py
> +        states={"draft": [("readonly", False),]},
Error E231.
Sehabis koma harus dikasih spasi 1

2020-05-10 23:02 UTC, mikevhe18 commented on product_category_workflow_policy/models/product_category.py
> +                raise UserError(_("Category %s cannot be set to draft because has child category") % (self.name))
Untuk sementara, fungsi pengecekan child ini dihapus dulu aja om.
Sepertinya perlu didiskusikan lagi flownya.
Contoh Kasus:
1. Product Category A punya 100 Child, kalau untuk mengnonaktifkan Product Category A diperlukan mengnonaktifkan Childnya terlebih dahulu, maka User perlu mengnonaktifkan 100 Child baru Product Category A bisa dinonaktifkan.
2. Product Category A mau diganti namanya, maka secara flow yg sekarang harus di restart. Kalau ada pengecekan Child, maka untuk merename, User perlu mengnonaktifkan 100 Child baru Product Category A bisa direname.

2020-05-10 23:02 UTC, mikevhe18 commented on product_category_workflow_policy/models/res_company.py
> +        relation="rel_company_id_confirm",
Penamaan relasi diganti jadi **"rel_company_2_product_categ_confirm"**.
Harus dibuat seunik mungkin untuk mencegah ada nama relasi yang sama

2020-05-10 23:02 UTC, mikevhe18 commented on product_category_workflow_policy/models/res_company.py
> +        relation="rel_company_id_valid",
Penamaan relasi diganti jadi **"rel_company_2_product_categ_valid"**.
Harus dibuat seunik mungkin untuk mencegah ada nama relasi yang sama

2020-05-10 23:02 UTC, mikevhe18 commented on product_category_workflow_policy/models/res_company.py
> +        relation="rel_company_id_restart",
Penamaan relasi diganti jadi **"rel_company_2_product_categ_restart"**.
Harus dibuat seunik mungkin untuk mencegah ada nama relasi yang sama

2020-05-10 23:02 UTC, mikevhe18 commented on product_category_workflow_policy/views/product_category_view.xml
> +            <field name="name">product.category form</field>
diganti jadi **"product.category.workflow.policy.form"**

2020-05-10 23:02 UTC, mikevhe18 commented on product_category_workflow_policy/views/product_category_view.xml
> +            <field name="name">product.category.list tree</field>
diganti jadi **"product.category.workflow.policy.tree"**

2020-05-10 23:02 UTC, mikevhe18 commented on product_category_workflow_policy/views/res_company_views.xml
> +    <field name="name">res.company form</field>
diganti jadi **"res.company.product.category.workflow.policy.form"**

2020-05-11 13:49 UTC, azmimr67 commented on product_category_workflow_policy/models/product_category.py
> +
done

2020-05-11 13:50 UTC, azmimr67 commented on product_category_workflow_policy/models/product_category.py
> +
done

2020-05-11 13:55 UTC, azmimr67 commented on product_category_workflow_policy/models/res_company.py
> +        relation="rel_company_id_confirm",
done

2020-05-11 13:56 UTC, azmimr67 commented on product_category_workflow_policy/models/res_company.py
> +        relation="rel_company_id_valid",
done

2020-05-11 13:57 UTC, azmimr67 commented on product_category_workflow_policy/models/res_company.py
> +        relation="rel_company_id_restart",
done

2020-05-11 13:57 UTC, azmimr67 commented on product_category_workflow_policy/views/product_category_view.xml
> +            <field name="name">product.category form</field>
done

2020-05-11 13:58 UTC, azmimr67 commented on product_category_workflow_policy/views/product_category_view.xml
> +            <field name="name">product.category.list tree</field>
done

2020-05-11 13:59 UTC, azmimr67 commented on product_category_workflow_policy/views/res_company_views.xml
> +    <field name="name">res.company form</field>
done

2020-05-15 21:06 UTC, merged