[8.0.1.0.0][product_template_workflow]
open-synergy/opnsynid-product-attribute pull request #38
Opened 2020-05-10 12:32 UTC by azmimr67

Product Template Category
Workflow
Make read only if not draft

2020-05-10 23:17 UTC, mikevhe18 requested changes

2020-05-10 23:17 UTC, mikevhe18 commented on product_template_workflow_policy/models/product_template.py
> +
Error E304.
Sehabis penulisan decorator, tidak usah dikasi baris/enter

2020-05-10 23:17 UTC, mikevhe18 commented on product_template_workflow_policy/models/product_template.py
> +        states={"draft": [("readonly", False),]},
Error E231.
Sehabis koma harus dikasih spasi 1

2020-05-10 23:17 UTC, mikevhe18 commented on product_template_workflow_policy/models/product_template.py
> +        states={"draft": [("readonly", False),]},
Error E231.
Sehabis koma harus dikasih spasi 1

2020-05-10 23:17 UTC, mikevhe18 commented on product_template_workflow_policy/models/product_template.py
> +        states={"draft": [("readonly", False),]},
Error E231.
Sehabis koma harus dikasih spasi 1

2020-05-10 23:17 UTC, mikevhe18 commented on product_template_workflow_policy/models/product_template.py
> +        states={"draft": [("readonly", False),]},
Error E231.
Sehabis koma harus dikasih spasi 1

2020-05-10 23:17 UTC, mikevhe18 commented on product_template_workflow_policy/models/product_template.py
> +        states={"draft": [("readonly", False),]},
Error E231.
Sehabis koma harus dikasih spasi 1

2020-05-10 23:17 UTC, mikevhe18 commented on product_template_workflow_policy/models/product_template.py
> +        states={"draft": [("readonly", False),]},
Error E231.
Sehabis koma harus dikasih spasi 1

2020-05-10 23:17 UTC, mikevhe18 commented on product_template_workflow_policy/models/product_template.py
> +        states={"draft": [("readonly", False),]},
Error E231.
Sehabis koma harus dikasih spasi 1

2020-05-10 23:17 UTC, mikevhe18 commented on product_template_workflow_policy/models/product_template.py
> +        states={"draft": [("readonly", False),]},
Error E231.
Sehabis koma harus dikasih spasi 1

2020-05-10 23:17 UTC, mikevhe18 commented on product_template_workflow_policy/models/product_template.py
> +        states={"draft": [("readonly", False),]},
Error E231.
Sehabis koma harus dikasih spasi 1

2020-05-10 23:17 UTC, mikevhe18 commented on product_template_workflow_policy/models/product_template.py
> +        states={"draft": [("readonly", False),]},
Error E231.
Sehabis koma harus dikasih spasi 1

2020-05-10 23:17 UTC, mikevhe18 commented on product_template_workflow_policy/models/product_template.py
> +        states={"draft": [("readonly", False),]},
Error E231.
Sehabis koma harus dikasih spasi 1

2020-05-10 23:17 UTC, mikevhe18 commented on product_template_workflow_policy/models/product_template.py
> +        states={"draft": [("readonly", False),]},
Error E231.
Sehabis koma harus dikasih spasi 1

2020-05-10 23:17 UTC, mikevhe18 commented on product_template_workflow_policy/models/product_template.py
> +        states={"draft": [("readonly", False),]},
Error E231.
Sehabis koma harus dikasih spasi 1

2020-05-10 23:17 UTC, mikevhe18 commented on product_template_workflow_policy/models/product_template.py
> +        states={"draft": [("readonly", False),]},
Error E231.
Sehabis koma harus dikasih spasi 1

2020-05-10 23:17 UTC, mikevhe18 commented on product_template_workflow_policy/views/product_template_view.xml
> +            <field name="name">product.template.workflow search</field>
diganti jadi **"product.template.workflow.policy.search"**

2020-05-10 23:17 UTC, mikevhe18 commented on product_template_workflow_policy/views/product_template_view.xml
> +            <field name="name">product.template.workflow form</field>
diganti jadi **"product.template.workflow.policy.form"**

2020-05-10 23:17 UTC, mikevhe18 commented on product_template_workflow_policy/views/res_company_views.xml
> +    <field name="name">res.company form</field>
diganti jadi **"res.company.product.template.workflow.policy.form"**

2020-05-10 23:17 UTC, mikevhe18 commented on product_template_workflow_policy/views/product_template_view.xml
> +        </record> -->
Dihapus aja om kalau tidak terpakai

2020-05-11 10:23 UTC, azmimr67 commented on product_template_workflow_policy/models/product_template.py
> +
done

2020-05-11 10:31 UTC, azmimr67 commented on product_template_workflow_policy/models/product_template.py
> +        states={"draft": [("readonly", False),]},
done

2020-05-11 10:32 UTC, azmimr67 commented on product_template_workflow_policy/models/product_template.py
> +        states={"draft": [("readonly", False),]},
done

2020-05-11 10:32 UTC, azmimr67 commented on product_template_workflow_policy/models/product_template.py
> +        states={"draft": [("readonly", False),]},
done

2020-05-11 10:32 UTC, azmimr67 commented on product_template_workflow_policy/models/product_template.py
> +        states={"draft": [("readonly", False),]},
done

2020-05-11 10:34 UTC, azmimr67 commented on product_template_workflow_policy/views/product_template_view.xml
> +            <field name="name">product.template.workflow search</field>
done

2020-05-11 10:35 UTC, azmimr67 commented on product_template_workflow_policy/views/product_template_view.xml
> +            <field name="name">product.template.workflow form</field>
done

2020-05-11 10:36 UTC, azmimr67 commented on product_template_workflow_policy/views/res_company_views.xml
> +    <field name="name">res.company form</field>
done

2020-05-11 10:36 UTC, azmimr67 commented on product_template_workflow_policy/views/product_template_view.xml
> +        </record> -->
done

2020-05-16 01:15 UTC, merged